const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{upy: 0},
	{unipma: 0},
	{background: 0},
	{judul: 0},
	{next: 0},
	{profil: 0},
	{Touch: 0},
	{back1: 0},
	{musikon: 0},
	{Mouse: 0},
	{instruksi: 0},
	{Audio: 0},
	{soal1: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{quiz: 0},
	{next1: 0},
	{back2: 0},
	{next2: 0},
	{soal2: 0},
	{back3: 0},
	{next3: 0},
	{soal3: 0},
	{abcan1: 0},
	{Text2: 0},
	{Text3: 0},
	{lagu: 0},
	{skor: 0}
];

self.InstanceType = {
	upy: class extends self.ISpriteInstance {},
	unipma: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	profil: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	back1: class extends self.ISpriteInstance {},
	musikon: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	instruksi: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	soal1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	quiz: class extends self.ISpriteInstance {},
	next1: class extends self.ISpriteInstance {},
	back2: class extends self.ISpriteInstance {},
	next2: class extends self.ISpriteInstance {},
	soal2: class extends self.ISpriteInstance {},
	back3: class extends self.ISpriteInstance {},
	next3: class extends self.ISpriteInstance {},
	soal3: class extends self.ISpriteInstance {},
	abcan1: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {}
}